name: Kicad CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:
  kicad-test-job:
    runs-on: ubuntu-latest
    container: 
      image: kicad/kicad:7.0.10
      options: --user root

    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: investigate
      run: |
          pwd
          whoami
          ls -la
          id -u

    - name: setup
      run: |
        apt update
        apt install poppler-utils
        unzip test.zip
        cd test

    - name: investigate2
      run: |
          ls -la
          id -u
