name: Kicad CI

jobs:
  kicad-test-job:
    runs-on: ubuntu-latest
    container: kicad/kicad:7.0.10

    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: investigate
        run: |
          pwd
          whoami
          ls -la
          id -u
