name: Kicad CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:
  kicad-test-job:
    runs-on: ubuntu-latest
    container: 
      image: kicad/kicad:7.0.10
      options: --user root

    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: setup_kiff
      run: |
        apt update -y
        apt install -y poppler-utils
        unzip test.zip
        cd test

    - name: run_kiff
      working-directory: ./test
      run: |
          ls -la
          python3 ../kiff.py -c HEAD~1 fmc_lpc_template.kicad_pcb
