name: Kicad CI

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

jobs:
  # fmc_lpc_template.kicad_pcb: failed to load with pcbnew, aborting :(
  # kicad5-test:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ghcr.io/inti-cmnb/kicad5_auto:dev_1.8.1-77724ad_k5.1.9_d11.6
  #     options: --user root

  #   steps:
  #   - name: clone
  #     uses: actions/checkout@v3

  #   - name: setup_kiff
  #     run: |
  #       unzip test.zip

  #   - name: run_kiff
  #     working-directory: test/
  #     run: |
  #         python3 ../kiff.py -c "HEAD~1" fmc_lpc_template.kicad_pcb

  #   - name: archive_results
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: kicad5_diffs
  #       path: test/diffs/

  kicad6-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inti-cmnb/kicad6_auto:dev_1.8.1-77724ad_k6.0.11_d12.1
      options: --user root

    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: setup_kiff
      run: |
        unzip test.zip

    - name: run_kiff
      working-directory: test/
      run: |
          python3 ../kiff.py -c "HEAD~1" fmc_lpc_template.kicad_pcb

    - name: archive_results
      uses: actions/upload-artifact@v4
      with:
        name: kicad6_diffs
        path: test/diffs/

  kicad7-test:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:7.0.10
      options: --user root

    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: setup_kiff
      run: |
        apt update -y
        apt install -y poppler-utils
        unzip test.zip

    - name: run_kiff
      working-directory: test/
      run: |
          python3 ../kiff.py -c "HEAD~1" fmc_lpc_template.kicad_pcb

    - name: archive_results
      uses: actions/upload-artifact@v4
      with:
        name: kicad7_diffs
        path: test/diffs/

  kicad8-test:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:8.0.5
      options: --user root

    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: setup_kiff
      run: |
        apt update -y
        apt install -y poppler-utils
        unzip test.zip

    - name: run_kiff
      working-directory: test/
      run: |
          python3 ../kiff.py -c "HEAD~1" fmc_lpc_template.kicad_pcb

    - name: archive_results
      uses: actions/upload-artifact@v4
      with:
        name: kicad8_diffs
        path: test/diffs/
