name: Kicad CI

on:
  push:
    branches: [ "main", "kicad-cli" ]
  pull_request:
    branches: [ "main", "kicad-cli" ]

jobs:
  kicad5-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inti-cmnb/kicad5_auto
      options: --user root

    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: setup_kiff
      run: |
        apt update -y
        apt install -y unzip poppler-utils pipx
        pipx install .
        unzip test.zip

    - name: run_kiff
      working-directory: test/
      run: |
          export PATH=$PATH:$HOME/.local/bin
          export PYTHONPATH=/usr/lib/python3/dist-packages
          kiff -c "HEAD~1" test5.kicad_pcb

    - name: archive_results
      uses: actions/upload-artifact@v4
      with:
        name: kicad5_diffs
        path: test/diffs/

  kicad6-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inti-cmnb/kicad6_auto
      options: --user root

    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: setup_kiff
      run: |
        apt update -y
        apt install -y unzip poppler-utils pipx
        pipx install .
        unzip test.zip

    - name: run_kiff
      working-directory: test/
      run: |
          export PATH=$PATH:$HOME/.local/bin
          export PYTHONPATH=/usr/lib/python3/dist-packages
          kiff -c "HEAD~1" test5.kicad_pcb

    - name: archive_results
      uses: actions/upload-artifact@v4
      with:
        name: kicad6_diffs
        path: test/diffs/

  kicad7-test:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:7.0.10
      options: --user root

    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: setup_kiff
      run: |
        apt update -y
        apt install -y poppler-utils pipx
        pipx install .
        unzip test.zip

    - name: run_kiff
      working-directory: test/
      run: |
          export PATH=$PATH:$HOME/.local/bin
          export PYTHONPATH=/usr/lib/python3/dist-packages
          kiff -c "HEAD~1" test5.kicad_pcb

    - name: archive_results
      uses: actions/upload-artifact@v4
      with:
        name: kicad7_diffs
        path: test/diffs/

  kicad8-test:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:8.0.5
      options: --user root

    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: setup_kiff
      run: |
        apt update -y
        apt install -y poppler-utils pipx
        pipx install .
        unzip test.zip

    - name: run_kiff
      working-directory: test/
      run: |
          export PATH=$PATH:$HOME/.local/bin
          kiff -c "HEAD~1" test5.kicad_pcb

    - name: archive_results
      uses: actions/upload-artifact@v4
      with:
        name: kicad8_diffs
        path: test/diffs/


  kicad9-test:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:9.0
      options: --user root

    steps:
    - name: clone
      uses: actions/checkout@v3

    - name: setup_kiff
      run: |
        apt update -y
        apt install -y poppler-utils pipx
        pipx install .
        unzip test.zip

    - name: run_kiff
      working-directory: test/
      run: |
          export PATH=$PATH:$HOME/.local/bin
          kiff -c "HEAD~1" test5.kicad_pcb

    - name: archive_results
      uses: actions/upload-artifact@v4
      with:
        name: kicad9_diffs
        path: test/diffs/
